/**
 * Bundle the Vercel Function entrypoints (src/net/*Entry.ts) into
 * self-contained ESM files under api/. Vercel's Node builder transpiles an
 * api/*.ts entry but leaves relative imports that reach outside api/ as
 * extensionless ESM specifiers — which Node then fails to resolve at runtime
 * (ERR_MODULE_NOT_FOUND). Bundling everything (app code + the Neon driver)
 * into one file per function sidesteps builder behavior entirely.
 *
 * Runs as part of `npm run build` (so deploys can never ship stale bundles)
 * and standalone via `npm run build:api`. The generated api/*.js files are
 * committed — they ARE the deployed functions.
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));

const entries = [
  { in: 'src/net/scoresEntry.ts', out: 'scores' },
  { in: 'src/net/versusEntry.ts', out: 'versus' },
  { in: 'src/net/experimentsEntry.ts', out: 'experiments' },
  { in: 'src/net/experimentsPushEntry.ts', out: 'experiments-push' },
];

await Promise.all(
  entries.map(async (entry) => {
    await build({
      absWorkingDir: root,
      entryPoints: [entry.in],
      outfile: `api/${entry.out}.js`,
      bundle: true,
      platform: 'node',
      format: 'esm',
      target: 'node20',
      banner: {
        js: '// GENERATED by scripts/buildApi.mjs — edit src/net/*Entry.ts, not this file.',
      },
      logLevel: 'warning',
    });
    console.log(`bundled api/${entry.out}.js from ${entry.in}`);
  }),
);
